<a href="https://colab.research.google.com/github/EzpieCo/PyTorch-Crash-Course/blob/main/01-pytorch-intro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 01 PyTorch Introduction

GitHub repository: https://github.com/EzpieCo/PyTorch-Crash-Course

Crash Course: https://ezpie.vercel.app/courses/machine-learning

In case of an question: https://github.com/EzpieCo/PyTorch-Crash-Course/discussions

## Chapter: Getting started with PyTorch Code

In [1]:
#@title Notebooks are the same as a normal python file

print("Hello Notebook")

Hello Notebook


### Changing your Runtime and check it

To change your Runtime go to `Runtime` -> `change runtime type`

Then change your runtime from none to GPU from the Hardware accelerator dropdown

**NOTE** _since you would be using a free version of google colab you will have a GPU that won't be to fast, but you can pay for a paid version, for this course the free one will work fine too.
._

In [2]:
#@title checking runtime with the nvidia-smi

"""
NOTE: This will work only if you have your runtime as GPU
Funny output right?
"""

!nvidia-smi

/bin/bash: nvidia-smi: command not found


### Importing PyTorch

In google colab all the modules are already installed so we don't need to use `pip` here. Just use the import statement to import pytorch: `import torch`

In [3]:
import torch

# Checking if pytorch is imported and what version it is
# My current version is 2.0.1, for you it may differ if you're viewing this course from the future(wow you invented a time machine?)

print(torch.__version__)

2.0.1+cu118


## Chapter: What and how to make Tensors

Assume you have a toy box full of colorful bricks of all shapes and sizes. Each block is allocated a distinct value. You can now build a tower by stacking these bricks together. The tower can have numerous tiers, each of which has a collection of blocks stacked on top of one another.

Consider each layer of the tower to be a dimension. Each block within a layer has its own position, which we can refer to as a coordinate. The coordinates pinpoint the exact location of the block within the tower.

These block towers are known as tensors in machine learning. Tensors are just fancy words for multidimensional arrays. It's like a mystical container that, like our toy blocks, can hold a multitude of numbers. However, unlike blocks, the numbers in a tensor can represent anything you want, such as image pixel values, temperature readings, or even the possibility of a cat chasing a laser pointer.

Assume we have a tensor that represents a colorful image. It might come in three sizes: width, height, and color channels. The width and height indicate the image's dimensions, while the color channels indicate how many colors are utilized to represent each pixel. Consider it a colorful edifice made up of thousands of tiny blocks, each representing a pixel in the image.

Links to useful resources:

video: https://www.youtube.com/watch?v=f5liqUk0ZTw (recommanded)

blog: https://towardsdatascience.com/what-are-tensors-in-machine-learning-5671814646ff

### Creating tensors

There are four type of tensors:
1. Scalar
2. Vector
3. Matrix
4. Tensor

PyTorch tensors are created using the `torch.tensor` you can read about them at - https://pytorch.org/docs/stable/tensors.html

#### Scalars

Imagine you have a box filled with your favorite chocolate bars (I hate chocolate!). Even if every chocolate bar has a mouthwatering flavor, there is something unusual about them because they each have a different sweetness level. Imagine arranging all of these chocolate bars in a row and giving each one a number to indicate how sweet it is. These figures could be zero, positive, or even negative.

A scalar is simply a single number, like one of those sweetness ratings. It doesn't have any direction or fancy dimensions. It's just a humble value that can be used to describe something, like the temperature outside, the age of a dinosaur, or the number of donuts in your belly after a wild breakfast adventure.

In [4]:
#@title Creating a scalar

scalar = torch.tensor(4)
scalar

tensor(4)

In [5]:
#@title checking what dimension it is
scalar.ndim

0

In [6]:
#@title Checking why is the dimension is 0

# We need to check what shape is of our scalar.
scalar.shape

torch.Size([])

#### Vectors

Consider yourself a treasure hunter examining a huge treasure map. You have a reliable compass that informs you which way is north, south, east, and west to aid with your navigation. Consider each direction as a distinct arrow that has a particular length and is pointing in a single direction.

A vector in mathematics resembles one of those arrows exactly. It has both direction and magnitude (length). It works like a magical compass, showing us where to go and how far to travel in a specific direction.

However, the fact that vectors may represent a wide range of values and ideas is what makes them so fascinating. A vector, for instance, might depict a race car's speed, an object's force, or a spacecraft's motion across the cosmos.

Consider a vector that represents the speed of a race car. The car's speed may be determined by the vector's magnitude, and its direction can be determined by its direction of travel, such as whether it is speeding north or east.

In [7]:
#@title Creating a vector

vector = torch.tensor([1, 2, 3])
vector

tensor([1, 2, 3])

In [8]:
#@title checking what dimension
vector.ndim

1

In [9]:
#@title checking why it's 1
vector.shape

torch.Size([3])

#### Matrix

picture yourself as a professional chef preparing a lavish feast. You have a magical kitchen notebook with pages and columns to keep track of all your recipes. Each page is a representation of a distinct dish, and each column is an ingredient. You should note the amount of each item required for the recipe at the intersection of each page and column.

A matrix is analogous to your kitchen notebook in mathematics. It consists of a grid of integers set out in columns and rows. Each number in the matrix is referred to as an element and can stand in for whatever you’d like, including scores, temperatures, or even the quantity of sprinkles on a cupcake!


In [10]:
#@title Creating a matrix

matrix = torch.tensor([[1, 2, 3],
                      [4, 5, 6],
                      [7, 8, 9]])

matrix

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
#@title what's the dimension

matrix.ndim

2

In [12]:
#@title why 2?

matrix.shape

torch.Size([3, 3])

#### Tensor

**_Already explained_**

Assume you have a toy box full of colorful bricks of all shapes and sizes. Each block is allocated a distinct value. You can now build a tower by stacking these bricks together. The tower can have numerous tiers, each of which has a collection of blocks stacked on top of one another.

Consider each layer of the tower to be a dimension. Each block within a layer has its own position, which we can refer to as a coordinate. The coordinates pinpoint the exact location of the block within the tower.

These block towers are known as tensors in machine learning. Tensors are just fancy words for multidimensional arrays. It's like a mystical container that, like our toy blocks, can hold a multitude of numbers. However, unlike blocks, the numbers in a tensor can represent anything you want, such as image pixel values, temperature readings, or even the possibility of a cat chasing a laser pointer.

Assume we have a tensor that represents a colorful image. It might come in three sizes: width, height, and color channels. The width and height indicate the image's dimensions, while the color channels indicate how many colors are utilized to represent each pixel. Consider it a colorful edifice made up of thousands of tiny blocks, each representing a pixel in the image.

In [13]:
#@title creating a tensor

tensor = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])

tensor

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
#@title what's the dimension
tensor.ndim

3

In [15]:
#@title why is it 3?

tensor.shape

torch.Size([1, 3, 3])

##### Why is it like this

You see the tensor here is having a dimension of 1, 3, 3. Maybe you can explain why is it 3 in the last, cause the `3` arrays have 3 values.

And if you guessed it right, yes the 3 arrays themselves are the 3 dimension in the second place, but why 1 in the first? you see we have an extra square bracket in it, that's what is being count as the 1 dimension!

You can view the image in the github repository for [better understanding](https://github.com/ezpieco/pytorch-crash-course/images/tensor-dimension.png)

## Chapter: Reshape, Squeezing and Unsqueezing

What do they mean?

* Reshape - Reshapes the input tensor to the defined tensor
* Squeezing - removing all the `1` dimensions from the given tensor
* Unsqueezing - adding `1` dimension to the given tensor

In [16]:
#@title creating a tensor for trying out

x = torch.arange(1, 10)

x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

### Reshape

Consider having a big box packed with vibrant blocks. A number is represented by each block. Let's imagine you want to arrange these blocks in creative patterns using a variety of shapes and sizes. Machine learning reshaping is similar to arranging these blocks to create new shapes without altering the numbers that are written on the blocks.

These are the main reasons why you should even consider reshaping:

1. **Input compatibility:** Let's say you have a machine learning algorithm that takes in images of different fruits and tries to classify them. But the algorithm expects the images to have a specific size, like 64 pixels by 64 pixels. However, your fruit images are of various sizes. Reshaping allows you to resize these images, like stretching or squeezing, so that they all become the same size. This way, you can feed them into the algorithm without any issues.

2. **Data manipulation:** Imagine you have a long list of numbers in a single row, like [1, 2, 3, 4, 5, 6]. But you want to analyze the numbers in a table format, with rows and columns. Reshaping helps you transform this list into a table-like structure, like [[1, 2], [3, 4], [5, 6]]. Now you have rows and columns, and you can perform various calculations or operations more easily.

3. **Model architecture:** Let's say you're building a model to recognize handwritten digits. To process the images effectively, you need to reshape the input data. Think of the images as jigsaw puzzles. Each puzzle piece represents a pixel, and the final image is made up of all these pieces. Reshaping here involves arranging the puzzle pieces in the right order and making sure they fit together properly. By reshaping the image into a 2D grid, you're allowing the model to analyze and understand the pixel patterns better.

4. **Error handling:** Imagine you're using a pre-trained model that expects input images to have three color channels (red, green, and blue). However, the image you want to use has only one color channel (grayscale). Reshaping comes to the rescue! You can reshape the image to add the missing color channel dimension, making it compatible with the model's requirements. It's like putting on a pair of magical glasses that can see colors where there were none before!

In [17]:
# Reshaping the tensor(1D) to a 1 X 6 dimension

reshaped = x.reshape(1, 6) # Reshape into a 1 X 6 dimension

reshaped # Output: error!

RuntimeError: ignored

#### Why we got that error

you see our tensor(x) has a shape of 9, cause it's from 1 to 9(index order starting from 0). Now if we see it totally makes sence that we can't convert a 9 value tensor into a 6 value tensor, cause then we will be left with 3 values not in that tensor

In [20]:
#@title perfect matches

"""
Now that we now why it's happening lets see at numbers that multiple to 9, factors of 9 if we say in maths.
so that factors can be 1X9, 3X3 and 9X1.
Let's put them in code
"""

first_combo = x.reshape(1, 9) # 1 X 9 gives 9
print(f'First combo: {first_combo}')

second_combo = x.reshape(3, 3) # 3 X 3 gives 9
print(f'Second combo: {second_combo}')

third_combo = x.reshape(9, 1) # 9 X 1 gives 9
print(f'Third combo: {third_combo}')

First combo: tensor([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
Second combo: tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
Third combo: tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


### Squeezing

Imagine you have a playful bunch of inflatable toys, each representing a tensor. These toys come in different shapes and sizes, but they all have one thing in common: they can expand and contract like balloons. Now, squeezing in machine learning is a bit like manipulating these inflatable toys to make them smaller in certain dimensions, just like squeezing the air out of a balloon!

In machine learning, squeezing refers to the process of removing dimensions with a size of 1 from a tensor. It's like compressing or squishing the tensor to make it more compact, without losing any valuable information. Squeezing is particularly useful when dealing with tensors that have unnecessary or redundant dimensions.

Here are a few scenarios where squeezing comes into play:

1. **Dimension reduction:** Let's say you have a tensor that represents the probabilities of different classes for a classification task. If the tensor has a shape of (1, 10, 1), it means there's only one sample, ten classes, and one prediction per class. In this case, squeezing can be applied to remove the redundant dimensions, resulting in a tensor with shape (10). Now you have a simple 1D tensor representing the probabilities for each class, without unnecessary dimensions.

2. **Model output:** Squeezing is often used to simplify the output of a model. For example, in natural language processing tasks, you may have a language model that generates sequences of words. The model may output sequences with shape (1, T, 1), where T is the length of the generated sequence. By squeezing the tensor along the first and third dimensions, you can obtain a more concise representation of the generated sequence with shape (T).

In [24]:
#@title checking the shape of first_combo tensor

first_combo.shape

torch.Size([1, 9])

In [29]:
#@title squeezing the dimension

first_combo.squeeze(), first_combo.squeeze().shape 

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))